banner: 
  charset: UTF-8
server:
  context-path: /kdTest
  undertow:
    accesslog:
      dir: logs
      enabled: true
    worker-threads: 500
  tomcat: 
    uri-encoding: UTF-8 
spring: 
  messages: 
    encoding: UTF-8
  profiles:
    active: test_dev
  jpa: 
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
---
#本地测试
server:
  port: 9096
spring:
  profiles: test_dev
  datasource:
    url: jdbc:mysql://localhost:3306/kddb?characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: sa
    password: 123
    initialSize: 10
    minIdle: 10
    maxActive: 300
    maxWait: 60000
  